export const pools = {
  titles: ['Ohjelmistokehittäjä', 'Projektipäällikkö', 'UX-suunnittelija'],
  firstNames: ['Matti', 'Anna', 'Kalle'],
  lastNames: ['Meikäläinen', 'Virtanen', 'Korhonen'],
  emails: ['matti@testi.fi', 'anna@example.com', 'kalle@domain.fi'],
  phones: ['0401234567', '0507654321', '0459998888'],
  postals: ['00100', '33100', '90500'],
  cities: ['Helsinki', 'Tampere', 'Oulu'],
  birthdates: ['01.01.1985', '12.06.1990', '23.09.1995'],
  drivers: ['B', 'B/C', 'A/B'],
  websites: ['www.example.com', 'www.mysite.fi', 'www.testpage.net'],
  linkedins: [
    'linkedin.com/in/matti',
    'linkedin.com/in/anna',
    'linkedin.com/in/kalle',
  ],
  summaries: [
    'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet...',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
  ],
  expTitles: ['Ohjelmoija', 'Projektipäällikkö', 'UI/UX-suunnittelija'],
  expCompanies: ['Firma Oy', 'Startup Inc', 'BigCompany Ltd'],
  expCities: ['Helsinki', 'Tampere', 'Oulu'],
  expDescriptions: [
    'Työskentelin front-end kehityksessä...',
    'Vastuullani oli projektinhallinta ja tiimin ohjaus...',
    'Suunnittelin käyttöliittymiä ja käyttäjäkokemusta...',
  ],
  degrees: ['Tradenomi', 'Diplomi-insinööri', 'FM', 'AMK'],
  schools: ['Helsingin yliopisto', 'Tampereen AMK', 'Oulun yliopisto'],
  eduCities: ['Helsinki', 'Tampere', 'Oulu'],
  eduDescriptions: [
    'Keskittyi tietojenkäsittelyyn ja ohjelmistokehitykseen.',
    'Opiskeli projektinhallintaa ja liiketaloutta.',
    'Erikoistui käyttöliittymien suunnitteluun ja UX:ään.',
  ],
  allSkills: [
    'JavaScript',
    'Node.js',
    'React',
    'Python',
    'HTML & CSS',
    'SQL',
    'Photoshop',
    'UI/UX-suunnittelu',
    'Projektinhallinta',
    'Git & GitHub',
  ],
  learnedFrom: ['Itseopittu', 'Koulu', 'Työkokemus', 'Kurssi'],
};
